# Generated by Django 3.2.5 on 2021-07-20 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReceptorCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReceptorControlService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('filename', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'unique_together': {('name', 'filename')},
            },
        ),
        migrations.CreateModel(
            name='ReceptorWorkCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('command', models.CharField(max_length=200)),
                ('params', models.CharField(max_length=200)),
                ('allowruntimeparams', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='ReceptorNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('log_level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info')], max_length=5)),
                ('listener_protocol', models.CharField(choices=[('TCP', 'TCP'), ('UDP', 'UDP')], default=('TCP', 'TCP'), max_length=3)),
                ('listener_port', models.IntegerField(default=2222)),
                ('listener_address', models.CharField(max_length=50)),
                ('certificates', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='receptor_node.receptorcertificate')),
                ('control_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='receptor_node.receptorcontrolservice')),
                ('peers', models.ManyToManyField(blank=True, to='receptor_node.ReceptorNode')),
                ('work_commands', models.ManyToManyField(to='receptor_node.ReceptorWorkCommand')),
            ],
        ),
    ]
